### ISSUE TITLE
requirement.txt error 

### ISSUE THREAD

**Issue by coder-code-byte** [271374667/SimpleWMS#2]
--- a/requirement.txt
+++ b/requirement.txt
@@ -1,7 +1,7 @@
 PySide6-Fluent-Widgets[full]==1.5.3
 loguru==0.7.2
 sqlalchemy==2.0.28
-pandas==2.2.1"
+pandas==2.2.1
 python-barcode==0.15.1
 pyecharts==2.0.5
 openpyxl==3.1.2

**Comment by 271374667** [comment]
收到，谢谢您的提交
