### ISSUE TITLE
运行 python 意外退出

### ISSUE THREAD

**Issue by tommying** [271374667/SimpleWMS#4]
您好，感谢您提供代码，我配好环境以后，运行的时候出现这种错误：

Path override failed for key base::DIR_APP_DICTIONARIES and path '/Users/tony/anaconda3/envs/py310/bin/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/Users/tony/anaconda3/envs/py310/lib/python3.10/site-packages/PySide6/Qt/lib/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/qtwebengine_dictionaries'

没有 qtwebengine_dictionaries 这个文件或者是文件夹，网上也搜不到，不知道您有没有遇见过这个问题。

期待您的回信，感谢！

**Comment by 271374667** [comment]
可能是你的系统之前装过PySide或者PyQt，有环境残留，你可以尝试下载源码从源码直接运行

**Comment by tommying** [comment]
好的，感谢
















在 2024-09-08 20:01:28，"Bemake" ***@***.***> 写道：

可能是你的系统之前装过PySide或者PyQt，有环境残留，你可以尝试下载源码从源码直接运行
